# build docs and uploads saves output as artifact for netlify_deploy_preview pipeline to be used
name: netlify_build_docs
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nim
        id: install_nim
        uses: iffy/install-nim@v3
      # this part might change depending from your project
      - name: install dependencies
        run: nimble install -y
      - name: Gen Book
        run: nimble --verbose genbook
      # the rest is standard
      - run: echo Commit hash = ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.event.pull_request.head.sha }}
          path: docs/
          retention-days: 1
          if-no-files-found: error
