on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v3
      - run: cat nimibook.nimble
      - run: nimble install -y
      - name: Test
        run: nimble test
      - name: Gen Book
        run: nimble genbook
      - name: Gen Book outside repo
        run: nim r examplebook.nim build
        working-directory: examples
      - name: Check book outside repo
        run: nim r examplebook.nim clean
        working-directory: examples

